/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of `Connection.schema()`. */
export interface SchemaSummary {
  nodeLabels: Array<string>
  edgeLabels: Array<string>
  nodeCount: number
  edgeCount: number
}
/** One entry in `Connection.graphTypes()`. */
export interface GraphTypeSummary {
  name: string
  active: boolean
  /** Number of node types declared in this graph type, if known. */
  nodes?: number
  /** Number of edge types declared in this graph type, if known. */
  edges?: number
}
/**
 * Shape of a node reference inside an `execute()` row. `kind` is
 * always `"node"`. Cast `execute()` rows to `{ x: NodeRef }` etc.
 */
export interface NodeRef {
  kind: string
  id: number
  labels: Array<string>
  /**
   * Free-form property bag. Values are JSON-compatible (number /
   * string / boolean / null / nested object / array).
   */
  props: any
}
/**
 * Shape of an edge reference inside an `execute()` row. `kind` is
 * always `"edge"`. Symmetric with `NodeRef`: `props` is always
 * populated, whether the edge arrives via `_paths` or via `RETURN e`.
 */
export interface EdgeRef {
  kind: string
  id: number
  labels: Array<string>
  /**
   * Free-form property bag. Values are JSON-compatible (number /
   * string / boolean / null / nested object / array).
   */
  props: any
}
/**
 * Counters returned from a successful DML statement (INSERT / SET /
 * REMOVE / DELETE / DETACH DELETE).
 */
export interface DmCounters {
  nodesInserted: number
  edgesInserted: number
  nodesDeleted: number
  edgesDeleted: number
  nodesModified: number
  edgesModified: number
  rows: number
}
/** Result envelope for `CREATE / USE / DROP GRAPH TYPE`. */
export interface DdlOk {
  ok: boolean
  /** Always `"ddl"` for catalog statements. */
  kind: string
  message: string
}
/** Result envelope for `CREATE / DROP INDEX`. */
export interface IndexResult {
  ok: boolean
  /** Always `"index"`. */
  kind: string
  name: string
  /** Present on CREATE, absent on DROP. */
  label?: string
  /** Present on CREATE, absent on DROP. */
  prop?: string
  /** `"HASH"` or `"BTREE"`. Present on CREATE only. */
  indexKind?: string
  /** Number of (label, prop) entries indexed. Present on CREATE only. */
  entries?: number
  /** Present when DROP failed (index not found). */
  error?: string
}
/** One entry in `SHOW INDEXES`. */
export interface IndexSummary {
  name: string
  label: string
  prop: string
  /** `"HASH"` or `"BTREE"`. */
  kind: string
  /**
   * `true` for auto-built indexes (memory-only), `false` for
   * DDL-declared (persisted in `.gdb`).
   */
  auto: boolean
  entries: number
}
/**
 * Open or create a `.gdb` database. Eagerly warms the LTJ TripleIndex
 * so the first `execute()` on the returned Connection runs at warm
 * cache speed.
 */
export declare function open(path: string): Connection
/**
 * Import a JSON graph (`{nodes: [...], edges: [...]}`) into a fresh
 * `.gdb` at `dbPath`. Overwrites the destination.
 */
export declare function importJson(dbPath: string, jsonPath: string): void
/**
 * Import a directory of CSVs (configured via `spanner_import_config.json`)
 * into a fresh `.gdb` at `dbPath`. Overwrites the destination.
 */
export declare function importCsv(dbPath: string, csvDir: string): void
export declare class Connection {
  get nodeCount(): number
  get edgeCount(): number
  /**
   * Run a GQL statement. The return is polymorphic — depends on
   * statement kind:
   * - Query with RETURN: `Array<Record<string, unknown>>` keyed by alias
   * - Query without RETURN: `Array<{ _paths, ...vars }>`
   * - CREATE / USE / DROP GRAPH TYPE: `DdlOk`
   * - SHOW GRAPH TYPES: `Array<GraphTypeSummary>`
   * - SHOW GRAPH TYPE / SHOW CURRENT GRAPH TYPE / VALIDATE GRAPH TYPE: object
   * - CREATE / DROP INDEX: `IndexResult`
   * - SHOW INDEXES: `Array<IndexSummary>`
   * - DML: `DmCounters`
   *
   * Cast the return to the expected shape:
   * `const rows = conn.execute("MATCH ...") as Array<{ x: NodeRef }>`
   */
  execute(query: string, limit?: number | undefined | null): unknown
  /**
   * Persist the merged base+overlay state back to the file the
   * connection was opened from. Mirrors `.save` REPL command and
   * SQLite's explicit-save model.
   */
  save(): void
  /** List graph types currently in the catalog with active markers. */
  graphTypes(): Array<GraphTypeSummary>
  /**
   * Lightweight schema summary derived from the live graph: sorted
   * label sets + node / edge counts. Does NOT consult the catalog.
   */
  schema(): SchemaSummary
}
